### PR TITLE
Better docs for Generator.integer() & Generator.number(). Test coverage added as well

### PR DESCRIPTION
**Pull request by Francois-Laberge-Bose**
- Better documentation for `Generator.integer(min, max)` & `Generator.number(min, max)`
 - Added test Coverage for both as well.
 - I believe addresses PR: https://github.com/francoislaberge/arbitrary/pull/5
 - Both functions now throw an exception if more than 2 parameters are provided.

### CODE REVIEW

**Comment by jasondonnette** [comment]
I believe you still need >= here:

```
number(min, max) {
    min = arguments.length > 1 ? min: 0;
    max = arguments.length > 2 ? max: 1.0;
```

Since it only uses `max` if there are 3 arguments. I'm currently using `Generator.number(0, 10, null)` in my code to get it to work.

**Comment by Francois-Laberge-Bose** [comment]
Did you check my latest implementation that I think makes it clearer in the code, at the cost of being more verbose:
https://github.com/francoislaberge/arbitrary/pull/6/files#diff-0569b48f4cf8bc27b28cf2e4868270d0R51

Also, these tests I believe cover all cases now including detecting having too many parameters:
https://github.com/francoislaberge/arbitrary/pull/6/files#diff-4663341696a08eef2606d83e7fb282a9R33

**ps. Just noticed I missed tests for Generator.integer(). BRB**

**Comment by jasondonnette** [comment]
Oh! Sorry, I misread the update. Yes, that looks great, thank you!

**Comment by Francois-Laberge-Bose** [comment]
Thanks for noticing this and doing something about it. The new package is now up:
https://github.com/francoislaberge/arbitrary/releases/tag/v1.4.6

**Pull request merged**
